# version: "3"

# services:
#   namenode:
#     image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#     container_name: namenode
#     restart: always
#     ports:
#       - 9870:9870
#       - 9000:9000
#     volumes:
#       - hadoop_namenode:/hadoop/dfs/name
#     environment:
#       - CLUSTER_NAME=test
#     env_file:
#       - ./hadoop.env
#     networks:
#       - hadoop-network

#   datanode:
#     image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#     container_name: datanode
#     restart: always
#     volumes:
#       - hadoop_datanode:/hadoop/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870"
#     env_file:
#       - ./hadoop.env
#     networks:
#       - hadoop-network
#   nessie:
#     image: ghcr.io/projectnessie/nessie:0.99.0
#     container_name: nessie
#     ports:
#       - "19120:19120"
#     environment:
#       - nessie.version.store.type=IN_MEMORY
#       - nessie.catalog.default-warehouse=warehouse
#       - nessie.catalog.warehouses.warehouse.location=hdfs://namenode:9000/warehouse
#       - nessie.server.authentication.enabled=false
#     networks:
#       - hadoop-network

#   hiveserver:
#     image: apache/hive:${HIVE_VERSION}
#     depends_on:
#       - hive-metastore
#     restart: unless-stopped
#     container_name: hiveserver
#     environment:
#       HIVE_SERVER2_THRIFT_PORT: 10000
#       # SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
#       SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://hive-metastore:9083'
#       IS_RESUME: 'true'
#       SERVICE_NAME: 'hiveserver'
#     ports:
#       - '10000:10000'
#       - '10002:10002'
#     volumes:
#       - ./employee:/employee
#       - warehouse:/opt/hive/data/warehouse
#       - type: bind
#         source: ./iceberg-hive-runtime-1.4.2.jar
#         target: /opt/hive/lib/iceberg-hive-runtime.jar
#     networks:
#       - hadoop-network

#   hive-metastore:
#     image: bde2020/hive:2.3.2-postgresql-metastore
#     container_name: hive-metastore
#     user: root
#     restart: always
#     ports:
#       - "9083:9083" # Metastore Thrift port
#     volumes:
#       - ./hadoop-config:/etc/hadoop:rw
#       - ./hive-site:/opt/hive/conf:rw
#       - ./hive-metastore-init.sh:/hive-metastore-init.sh
#     command: ["sh", "-c", "/hive-metastore-init.sh"]
#     environment:
#       - HADOOP_NAMENODE_HOSTNAME=namenode
#       - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
#       - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql/metastore
#       - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
#       - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
#       - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
#       - HIVE_SITE_CONF_datanucleus_autoCreateSchema=true
#       - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
#     depends_on:
#       - namenode
#       - datanode
#       - hive-metastore-postgresql
#     networks:
#       - hadoop-network

#   hive-metastore-postgresql:
#     image: bde2020/hive-metastore-postgresql:2.3.0
#     container_name: hive-metastore-postgresql
#     restart: always
#     environment:
#       - POSTGRES_DB=metastore
#       - POSTGRES_USER=hive
#       - POSTGRES_PASSWORD=hive
#     networks:
#       - hadoop-network
    

  
# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
#   hadoop_historyserver:
#   hive-db:
#   warehouse:
#   hive-metastore:

# networks:
#   hadoop-network:
#     driver: bridge