version: '3'

services:  
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - dbdl

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - dbdl

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      - mysql
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dbdl

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_USER=root
      - POSTGRES_DB=mydb
    networks:
      - dbdl

  orchestrator:
    build: .
    container_name: orchestrator
    command: python main.py
    depends_on:
      - mysql
      - celery_worker
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dbdl

networks:
  dbdl:
    driver: bridge