[project]
name = "data-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyarrow>=20.0.0",
    "pyiceberg[nessie]>=0.9.1",
    "pyspark>=4.0.0",
]
