[project]
name = "data-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyarrow>=20.0.0",
    "pandas>=2.1.0",   
    "pyiceberg[pandas, sql-sqlite]>=0.10.0",
    "sqlalchemy",
    "cryptography",
]
