catalog:
  default:
    type: sql
    uri: sqlite:////warehouse/pyiceberg_catalog.db"    
    warehouse: hdfs://localhost:9000/warehouse  # Your warehouse location
    # warehouse: "file:///tmp/warehouse"  # Use local filesystem